export enum GROUP_LOCATION {
    LEFT_1 = 'Left 1',
    LEFT_2 = 'Left 2',
    LEFT_3 = 'Left 3',
    LEFT_4 = 'Left 4',
    RIGHT_1 = 'Right 1',
    RIGHT_2 = 'Right 2',
    RIGHT_3 = 'Right 3',
    RIGHT_4 = 'Right 4',
    CAFETERIA = 'Cafeteria',
    OTHER = 'Other',
}
export enum GENDER_TYPE {
    f = 'FEMALE',
    m = 'MALE',
    x = 'MIXED',
}

export enum MEETING_TYPE {
    TESTIMONY = 'TESTIMONY',
    LESSON = 'LESSON',
    SPECIAL = 'SPECIAL',
    OTHER = 'OTHER',
}
export enum LESSONS {
    LESSON_01 = 'DENIAL',
    LESSON_02 = 'POWERLESS',
    LESSON_03 = 'HOPE',
    LESSON_04 = 'SANITY',
    LESSON_05 = 'TURN',
    LESSON_06 = 'ACTION',
    LESSON_07 = 'SPONSOR',
    LESSON_08 = 'MORAL',
    LESSON_09 = 'INVENTORY',
    LESSON_10 = 'SPIRITUAL INV. 1',
    LESSON_11 = 'SPIRITUAL INV. 2',
    LESSON_12 = 'CONFESS',
    LESSON_13 = 'ADMIT',
    LESSON_14 = 'READY',
    LESSON_15 = 'VICTORY',
    LESSON_16 = 'AMENDS',
    LESSON_17 = 'FORGIVENESS',
    LESSON_18 = 'GRACE',
    LESSON_19 = 'CROSSROADS',
    LESSON_20 = 'DAILY INV.',
    LESSON_21 = 'RELAPSE',
    LESSON_22 = 'GRATITUDE',
    LESSON_23 = 'GIVE',
    LESSON_24 = 'YES',
    LESSON_25 = 'SEVEN REASONS',
}
