import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'MEETER test',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`bg-white dark:bg-gray-900 text-black dark:text-white`}
            >
                {children}
            </body>
        </html>
    );
}
